title: Janelle Williams
logo: <img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/26cba116-e315-4694-a2b4-8ba92f3948d3" />
description: Business Data/Tools Analyst Portfolio
#show_downlaods: true
theme: jekyll-theme-minimal
